apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data
  namespace: metabase
spec:
  storageClassName: seagate-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
