---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: platform
spec:
  encryptedData:
    .dockerconfigjson: AgBacihAWp+C1XQYbbze8lLBpAO4NmFJQ/5KRK7Jza8KkjHhadPvfQRuHuevsqEFPk/3mlbd0SFZp9OPDBrQfyzqVn++xNnO8egAgGhnChx2A2FWRiR8enH3Mgyw5OUdVAGCsX8j6lgM4fpyHc0RKf37QjKzq/ZbQYnxNeUjAzmUq9RHCmVd5Q6b8JeVSonEkQH3FcBYSjiYC9RwR4FUjbx4CvVi/QY2neCV17er7lH36qp5Zav0zozvMDsmNN+0BLAvINql/kU2qnk2K2JrF4c5zpU6+Dxd9HsMOdlZsX/4vFfoZ/mNWbpSXyEL/GnLv2H3jtgdAHjehvvJHBIJa/666P4jBS/oK7UkuUuw+bDYI9Lfg74R5uvK7TkaNMSdaE5uZ7tHiKPhQvvDsjJdI4zTmU3H5ecC12Eq7Jn7aKKQI/kSYH6V2FEAFdia+K3tJqtf8OcnmMk8o/PiAxZNb3fH1q/gynbKDJOPw1gHmErbvf20d8e4I0O22Er/VYzUH1O/CiemHjh6SiheltqPEz4hv+Dtus6FIwnIM1mSxRvjAuidm0y4aNb/g+a7fXyzSxnLtb0huSTTw7gt542I+5Rt3HUMHbi+4qcx+Rr0eQz7As7DSMO89a4zlQ5r3mf1JgIpweTLSs4XIIc4raxCTNtnjLgGWKIpfQlBCaslVQE5rZualXI7RX+ffOdA2Nd96k5l+i3flNCIDSP7svL/L7pHwmK8G1SliBwDXdn0nnIxfwy79hvxm0iovqEviO0Kvi5f706/7Gubt0btNgpZ0U8BeXMIhj2TU5zlNwwvmOzy/UB2oTTPll7DshJspkzWdiDJ/k19zxXAzeUOhCunheCmMR7hrvVjF8pCapzvuL7gqylNc3P0bdzdGm2IzNhZ/LAuRZnureTk4dJJzU2OCWLzqb1n13ttJO9fMIgK1xCEEhQ=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: platform
    type: kubernetes.io/dockerconfigjson
