apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data
  namespace: nocodb
spec:
  storageClassName: seagate-local
  volumeName: nocodb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
