apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: https://ntfy.ininicho.com
    listen-http: :80
    cache-file: /var/cache/ntfy/cache.db
    auth-file: /var/cache/ntfy/auth.db
    auth-default-access: deny-all
    behind-proxy: true
    log-level: info
