apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  storageClassName: seagate-local
  volumeName: prometheus-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
