apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: postgres
spec:
  storageClassName: seagate-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
