---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-auth
  namespace: monitoring
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgApefY1hM1eezI3//XtiKpkFruPmZVlGlnp5js3Bu/tMQ7n7kq+bgMjhdN2cWfRKektkJg0XABfzpYyFS1Ue28ZPkgEOV7l/FjPY+86EoYnkTanqgqju9fofvuWpyJU6G358iLR3lWSYodma5b/P2fTtd6iPaL02L7BHusaczceh/8Icj6SUb5b5XgQV1sWErqDjaVTZmscJ58TCqDB6vIg+YlXTX5RbmQYEM5aekyg2QDn4D1e7b1LgVW7G9T1OSeMLlM1jqDlfnwCY2sEAWJhAXi9xnlq4z+Kh44OKS4ooTx+rYczboVlEwUZReww3rXmrDWcpx1rxkRMWATUib+xIWPDJ1MvyD1XzJ8kqWrfG2/Z3Y7oQFTbkizCuHstJnwKULlnqWTAV2lZNmpP+c30NsN1Njvz83LOGdhBomsDxIiGgWiUtixGbiWMnozeiE5gYcx9DfUra++rDs9yW4oRKwKBeLusex0pybF48sT+55CappTUnRX9tIPhvQrkhNzIiZCs4TWTK5QH0A45alrufIQHCelLds4gk1q469dFuSpVLYM3F52LntRyh4JZ0qn5ugioVj08fE7+JCC40Ib8sMUOUC1DWxIq/ExpVfEUpdenlesnqGBeB4x20dImq7NGx60shzaFqkVFMVZAgEomQt+rP0/Gr4/KFPPhwGjFcWV2UGQrjndifV2R6aK+6Ad8IdIZsuLhn+PZITgjv1f+
  template:
    metadata:
      name: grafana-auth
      namespace: monitoring
