apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - command-runner-auth.yaml
  - grafana-auth.yaml
  - metabase-db.yaml
  - nocodb-db.yaml
  - ntfy-auth.yaml
  - postgres-auth.yaml
