apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - command-center-auth.yaml
  - grafana-auth.yaml
  - metabase-db.yaml
  - minio-auth.yaml
  - nocodb-db.yaml
  - ntfy-auth.yaml
  - postgres-auth.yaml
