---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: metabase-db
  namespace: metabase
spec:
  encryptedData:
    MB_DB_PASS: AgCwEACt0BuUQs1DcsFB/O5UPDwTtn/MLvzpdP8Dd/0V9Pv09uqaS0g9GF6+71p7JOMR+xNAN3M7aKh1kQ2z6VjtlNAfVa4Tun2qcfcm7o5MYAS7JTnjbD+nrQqOtPPQ1Ftu9mAmaX4LpxcG0ZxxalUD7GpO43rFHPbFAPH9Uw+sNlZka3WGVYWQd+cOIJCyyBpUPVXTIBHACQ3m9eTjDmdZPbPDCd3A+voqn8kSX0Bdj11z741aACZYWW1iRAMAJScfnNXsxAoA78HlhwmosRcqwB8c8qXoSVgrR7tcTVnng0PiOocI4Ac3xuVHNexRwtZyAuC/PuzPlCHcXeVAR4cRUEZuBRLE6TOvlDl8kTCNuqPRzQsMFWF4ntLZUq+Vu11ynz9L6Ovmv37xx+vkrqAH3RQnnOJoA1vJwAOiELxOOBOs0wR09mEhdkrTspo9oO4vgu3ud0hrVWUPywO50Tg0CZL/kViZ1+45OwGpvjeuoYd2zy2mst9QoFDRl264j2lAO/EO3CG0NJU3e+utyVlrMVQRoBkpgTJxwsDhK7rQs0DDZpj9njSCtYfwpWlI6a3XHPND3SaMZB0oHHZ10sVoUDckAzjWIe/XQrpMZ60nSvqsgvqkWEOh0dnufxsOmobSOW2+JAf6yywwGQUAaJRE1vbIm/Zi3Dqg/CZFcZgTP5fA8NfCavrSvhbwXvwKwCnnQdbMt6c9GQu9XOg=
  template:
    metadata:
      name: metabase-db
      namespace: metabase
