---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBPX2R+bjlcDOgGou6OsQrnnKkYbVlQSima+YsW7E/UEowNAeaEPFeeSt6kEimWwsSxWNLT1bl5B9gFzrsWwleZ6xs3SnvLnPc/SiExA7L9P7n6pN7Pp8HcyPFyOypovlrZk6wfODbsAsubcqoSWygGQ7W6uMB8GNSoCb8JFXoIsIG4vweVOPcfjRSSlZcfuiMWd0XieSinr9JgNEqe0EWCn1hAZ/+W66u1xsSz0YAzQF6Vcuo52DztD4qQ2zNulzyq5TI8DE0DMadnU3/oOFSHo0zccI5Yqy6kZYZom+oGC6jpzLk7NSkXqohgrqSMLFC+gjcNuFcpUQeKl0TeQ5hzNg+JBmUgJAlk3hdrFxFDKo5UFmQHZTtBQjD2OegPR8rpV5x28ICgGhf7HOh3uzWUyW2EgFyp4gy7U7izLED4Xv8WkvIqvLMhIUGJz8MbunylC/e0FB09udnal9dJUtf6Btr3JvXmPcX6ATm2MonwCNmh2SEaiwNqBDn94JnqsmBe+yk1xgBF04WVjnSkFzXrrKKGdDdaXDq3aXOMnGPqcXUI9M7S/TzgaZ4S0sCcRdwWYdE1JZXxKMNfVotLhEN19c7tq9VKboUa9bsPRVcTnsoqXlPrQgL6566+ta2Ya5ats22A2DzBG/TbVYp9QFB4Klfz8+k/sNfFJdEpKHBtKfYC6GkTLe8oUk3oftJkovEhLUMuI4tOdpAcmkD+QnCW
    MINIO_ROOT_USER: AgByFmtzUGgcauTxRMqqCO64TjJSqNF92oLI5IcnMrvelZp7J4nA7fT6BdiY5OUTO9DahRGD/J6Bopt1SQzNXnTGVqyWPUaIF5V3X5j42eWVDp8m8TgQyeGuA3UvFiI0ZYfAAXV6F5tl9hM8IkB58JyaZXjKQfp6NoKxj5pKfv5Cz+QZ7A+Fsv3Uu1TMopyyk7sOvH7f0xwr+QGoWoqIBZyI2WYT2tu8wxeTNd2V9XHnKj4Zy/yi8ERGPdahGvSk2XLkATqFVpx5+4JyM+k7s0YcHJrfk/IvwkcoHaWvW0sCB67QQMNpZ+maQsF2v8XTKLSZhYp+u1aGOZEhKWtlP+v5p2YNzg1JsOKYCjsKP3G20XEejZEM9F9l8YjW0x3q3fPFQWgY2I66UTdXwxe9rglI42LwJqr78qtxYotM49VDaAd1tPgcRP+eqczRv2KSnYJ8DlSUmFUNRzzPqKRlfyW5u0SOq8phHVbrYRQNA/aoKiP+B2rTyhTk/vEnL2BZONUJRbqJ9gtOaRUExc85w5gW/94kxByYpDJEWgxiCGAAlcn6VVfqsywELBcWSqNwkhgP2h5y1PdgBdT+J/XtOjWDSuXvTPvUq23yCqpuVDkbwcsiH03kkS/0MmeQtq9zw5miNs7wtQDreTSdLNDXJEAxxVs7oaw++K3jD8K8sitJz0iSIZrwHPlQ+HxfE6cH2mUwXdjYnA==
  template:
    metadata:
      name: minio-auth
      namespace: minio
