---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nocodb-db
  namespace: nocodb
spec:
  encryptedData:
    NC_DB: AgC5XbggsGhxM7qauLy1alDe6UZWAzRunvPaUxqAheIvSngct+UCaaPcMMXl0HLpvL/MnO7m9X2mYY0hhmJFJ1ZJuPlfW39FLMe1E58sn5lZycDKu7RdoqnzJ3kNHhTooisLQvxFtWhYqeRPi9rj8bq7Y4QLRipjJU3BZdiJpTIy4UHmnoXVhyxQNP9L2h2dbBsQFgyYWBYClRNgG4ffHaNNSvxiOXdxCtv69nGjhM4d1xCjaD+N5numgdPQ5rWwTGoda+sNQacnhudOvQiQrHJrAm5PnbfPe1GpKSlYZjcbSPZQ1V6oreKkCcSweuBJZgJAyDUoK3C6wpvjHnqf7dO+j8JVKRP1iwwl9lfjE6LJBiDedI+ACjwglQ5JIaeyqrgilYEoxnByW1i4BypGTvgyI4Tvyr9CK9oUTQN3QZTlqQby7TncqOeVQXSVP6h377LP75uK0PnTQFR3+8xFamc6DSkiXnP4q1TmUdpZOPP1LTJaB/t9JWnAWWsOildYqGWQyPsC+KdtBifVsMIcj+a3CDMrvQ5JEWIfmGnhDMPoIZiPPNu/PvIQKzEq85cgWdnO6nGj+0EKD9uABovmpiQKxcs2U/7aGozNlw04k5Z0qc/egebul8KdbhmGZX7vUu159xFhJfN4rr4IuqT25ASXePC7515cjEymhjRGWLonlNCJ2Zz+bwveb1B9sf+QEuv4yPsDBYSnMgMcqeHCiDeveGFeykCToFXViUi2dA4eIyGP4ydWxMHFuNwNLnRwVkDk4IiKyfKnaKJyJPio4hsWWam/Ro3AO7WVc6uMN3/AbQ==
  template:
    metadata:
      name: nocodb-db
      namespace: nocodb
