---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-auth
  namespace: ntfy
spec:
  encryptedData:
    NTFY_ADMIN_TOKEN: AgBt2ZuTrgbqhnapBxUzmJdi2YRS9Erv34a1dVs75eTiv+C2ejHuK62Nb/5jnxTfSY/2TPnGCdGtvlatZu/R3V/wwdP7wiQYFgnfmKQc85UVCd4dMF9UteWsZOwI6UqNbOihvc5cZfE3R7r4wNyRd6QK/GNPpkqfa6fGB6DIzwxRCB6jDwihR4f5Sees7cmiTchHsvZFGSPt9zK/v2WC/6oKORw0/957NvAqMpY7JaQB6Z3Q6qiQZnnAsguooC8sYgk9ayptr/+3wEgREFY4Edx8k0c20VyiFiJ+Awvfsh515mqhpxNcYx3AE+LHCOeVK95+wgwC8vYnKEYVuZGpEvs7c2Mye2/CyIzmtqvxtpwBKXRxjDathAmmnxpzQXyf1qnRy/JJ9pAb8c1yAJOdWmwVKEj74E0gQqcIjw9agaEQcYHjyjSU6Chiek+aSSOMZkuh59MMyGJE4nQ7DMMKhtU+L8I6Nez9r7LjCyTrXjoBgKsBxzYo88kiDImDCD6kCQOGDP4rAXgoIU4HKu4TpSrCVV+nlVE6ENLc4iV/Y6dFxLATat9Rr+SpVspU8U6+iJcDLBa6a9VmUTIxed5pagDDb+1B2XB0YmhXkyBmaoqk8ORSGGG8QXHIE2XIElgaE2tPhV/LN10g879nJYKxu0QEQPjDJF1WbD7KeTZFTJim2qA3tn8vWgWPlu9d+WoWzVakalCXuiN7mCqjraxyPu8CJKTev2MDbhdZ+6pbWpe/mg==
    NTFY_PUBLISH_TOKEN: AgAD6E3jOm1KrmzWAXEgMGADUKCQE6o9E1PODC00MtXqksw+CVZMyXVIllHWN1jCW5u7UgVODsRSKcifl8yTRGYhGNuLCXSACXzOqhx1n2icWE4HOszLUeTGlyyBYLeQqmPNfBlYwtWYQgAcMCp3Q7QBbbr1cvOYGnMMyCeLuq7qUhu7Umz+kFNETCA7Vuq5HO6VY/24mhJalV1Ryzg5TQF9aXX4eT9iOg9+EBbyD6A/V+E3cQ5MnQeswcOditrID30lr+Yd1aHyl9wcIrPNTh5yISBcrEOUH8O+WxMRGnkNMDxI9oTj+gunXUZmu3O4FX/2gX0+idvdQ7UBrGRw38MQMyM4NsQjVqICyKvBpdVIrAn4x74mAZqMMr2RYS9AZNQgtGAELPAgS9EqG4A08oxwV4+sLPMhFuphRC2X8l2g8jqEmxoSGnL8pDGnljXQAbgMNOfgT1OTn4fxRNArSgMzNjlDxZp7v3VTXUcHHydGWoRHaj1X6BhJ499t/NHuds5dgnTsf2x/vb4NhKm9WdyFb9CsxiiC9qtv2omOPjhPdfaOC6+53BKZBbWi3KgHOa9KAAWQHoLIZsezmEX2f6tW1mlzsmu8/3vhR+uV36FqnQkY/iRpDXNkX/wEoxSSqeP9MokHte8klgFJf6LbKWd9PaWfhiJIUWRT8WWcMn+Mgp4mckYyieaOphzUO6A1rJE8UEqzUchOBXHhhV2Zk+7tRiieM+1TOq9BEIdE7I8LgZthjovB7ieSMWBc26+Nc5KWCYQ2Kb6mV/ZOMbU+REJd
  template:
    metadata:
      name: ntfy-auth
      namespace: ntfy
