---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCK5Drja2heVXwt5gzT+uNCXdRZduZAm9lwdoxonlQvC243ftDNnA18s+F9DvPjZbb9+FpUBhfzgYB37zpQzv2f5+tOMp1zTO9idXkRsVRx+5PmSG8HWTwXufflqVVYSTVcRUY/t/6UpF6zXhZtSVcTmlMtJd8908Ws/wW1aLrIjKzsGIxJqO0iDF0q6QqkErSV8Fhwqntq9+D/jh0kFU24iFia3tLWpCDcgB3zRFISpxPY4LfYudPj+jZjmn4aBoNmHUiX2+wmbpEvD48GRNDnM9vyS7xNvibKn5aHYr6Z5K/84TrvyyyjgCvA08Hcr046gxOw/gfR0/6o9o/UalRqW1VUuLUY/NiuFODbQZ41tmScSAi8/sg3LkbyIHrT8HPD//1m7C2e5hx5KlD88RXUEz/+g+x3UNaCMvO3nd+wOw53rXYQKQu8sLYAvlDr95IjwlyxGZC1kGLHryRlbv7TEqlFpz/dfGwx3XeGWfccM97zCiLOnZ5uYA8zk7zLYDKYNODIK5hYRwmtC70zk6FN6dIopn8JjfqBlgHwapl0BcwkWvjSAGoPX67sBtBHQSVvvZZsfcU0zULdLYtFzrlg/KXdyR4JYyEDhO685sWeY8tMjqlXsn0HF0V0hBIu5O7UWMHkzRGK4p8MFBQvLe809icn1DFcY1CQp15N5+x1Dw24ZYw8RS1kMyudYD4UIW3YBYua1TmRUmPerL4=
  template:
    metadata:
      name: postgres-auth
      namespace: postgres
