---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAPDRNipAFuImpHvVo7Ar+1Z3BqE+SAjlr75dEJlQpg5DWNEnILP9JvHwT+vVkcWjDNpiQqMkl6sF0C0mOgUX9t6bBooZclp+ty78GM+DO9BfyaPH7DR+ix64D4iZqaJelAknb6DM5JAyOn2Yr22yqocXq1cDr66jcMl2klTMFfjoV4hz9AxwEsr8/y/e97ItXK1f1D2FLrv0i3dwuWMVmm+v9K8kIFiSXu8oZJbZchGUBAuk2b+pGb0Te7aJ4LwALgvBQq4Ujm06WL7wxcD3K6/ZFrP7yRQffAqbGdUeTuUf9ZOOdulBPjYx38O8iF9r1km1Azu8OT7YYRZwb5TpKq3P+gKvcMcCE3FfFlWHeBxn6PfXIZodeAo/KU8UEMRzlDRpMWYn6kRtpDNWo14BVjE4otr8rw172vf77lsFPLgE9f+t65DLGgOTeE3I7lUjj8JrecZxHBp8WH20dDC+xBGVJAuJ8pCqKhTtEyX8YRXLvmi+C4+2TOEVpO2DzR7hp9Ij2vvEQ3ygFghTdEWGgJFIZ5RLnwDTd0zpW6AyO7Di/8SNN9e21AIEKdy2MO3DhgpdU0y+CEaYqhKaw7bYaubM1eBeCIQmSLHNZEr/UjXsIZ0YDc+Z+OdV1zM/W/Xx66nLHZCR/cy/47BtmzSFmz9HYh09v/pkAgmdpc2tGAlX0apagPefg83PfehsotDTX2ofPQP0P1pw==
    RUSTFS_SECRET_KEY: AgAfyY3v0V71GWhKVp81Qef00UYsZTf9445OV05NPlXP2YVaDAlSTN3iZOS6vuwyhpFP1j86+nnonLi7bFHzJ8hSOl4t1lxRNVa65OSB0tHOILIKTX5qeTYW2F7cFdnAXSNDZq4dazd147VBNdfcMoLq/eQc39pVg1cjEozVDof9HKPjqGglXHlAG5+sUoCRyKs3rRihh+SyIqHYozjuWa+3bEN51fjNPen1DsY0UFri/1YVWA7lG0V9GUlHbqQAykaIl4ZxXrZIzvgL3oE6nl0fdUIwH815/XGJEYgbOF36wXRMbEw0VYi1rohboEXx8lFRVNNlLiJe0SVO1O5MPAYGo+F4qmDECzMSzaahFEYhCH3v9pmKvx26dOgyhSBa4lclxNYePChW1skcOxd1P5hlfFNTLXdrnRs9CJ/mWxEPNcjQVk8MhHHlDtHtXFHp/HmIZQyCoo6inN4m7ZNaSdoPFhbFaPrdSqOE+MiW6kZqB4BILKd10437vUX+ZEYysttVfyxvTJ9g4+ld6DNoowGudGJhYOOS3bGYRaZbQzqxCmsoUEjXtAlKFRzI7qRL1z+FPGMEshTzOvOZ3FOSkWC+E4CrE4pMaS/7q1GvucmUqGZLoNew7DoDi0HFYyCVBrSabrf7wi9hivYeS4LzHl8F+0MvukNYaDo0VnQ9JN8fKNt+rCipkzpnOh9jyZsyyP1lr+ItsPeEyNM=
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
