apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: redis
spec:
  storageClassName: seagate-local
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
