apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: command-center
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ininicho/ininicho.git
    targetRevision: main
    path: infra/homelab/apps/command-center
  destination:
    server: https://kubernetes.default.svc
    namespace: command-center
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
