apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.rustfs.com
      chart: rustfs
      targetRevision: 1.0.0
      helm:
        valueFiles:
          - $values/infra/homelab/apps/rustfs/values.yaml
    - repoURL: https://github.com/ininicho/ininicho.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rustfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
